### PR TITLE
Create idsclientlib.conf

### PR DESCRIPTION
**Pull request by saqib-ahmed**
Created a sample config file.

### CODE REVIEW

**Comment by dekwan** [comment]
Hi. I will pass on your sample config to the uccx team for verification. If they give approval, I will merge it.

**Comment by teshvvv** [comment]
@saqib-ahmed : I am from the UCCX engineering team. Thanks for raising this PR to help fellow developers.

Can we please rename that file to indicate it is a template and not the actual configuration file?

May be name it as idsclientlib.conf.template

**Comment by saqib-ahmed** [comment]
@teshvvv Updated the name of the file. Thanks for the comments.

**Review by teshvvv — APPROVED** [review]

**Comment by saqib-ahmed** [comment]
@teshvvv Can you please link this repository in the documentation here as well: https://developer.cisco.com/docs/contact-center-express/#!cisco-identity-service-client-sdk-guide/overview

**Comment by teshvvv** [comment]
> @teshvvv Can you please link this repository in the documentation here as well: https://developer.cisco.com/docs/contact-center-express/#!cisco-identity-service-client-sdk-guide/overview

I donot have permissions. Will defer for @dekwan to consider that.

**Comment by dekwan** [comment]
Looks like I did write that documentation. :)

I am thinking that a headline called "Additional sample code" can be added with the link to the repo in the Appendix: https://developer.cisco.com/docs/contact-center-express/#!cisco-identity-service-client-sdk-guide/appendix-sample-code

Would that work?

**Comment by saqib-ahmed** [comment]
> Looks like I did write that documentation. :)
> 
> I am thinking that a headline called "Additional sample code" can be added with the link to the repo in the Appendix: https://developer.cisco.com/docs/contact-center-express/#!cisco-identity-service-client-sdk-guide/appendix-sample-code
> 
> Would that work?

Yes. That'd be great.

**Comment by dekwan** [comment]
The link has been added here: https://developer.cisco.com/docs/contact-center-express/#!cisco-identity-service-client-sdk-guide/additional-sample-code

**Comment by teshvvv** [comment]
> The link has been added here: https://developer.cisco.com/docs/contact-center-express/#!cisco-identity-service-client-sdk-guide/additional-sample-code

@dekwan : Please change `UCCX IDS` to `UCCX IdS`.

- IDS: `Informix Database Service` or `Intrusion Detection System`
- IdS: Identity Service

Our Cisco IdS caters to Identify Service.

**Comment by dekwan** [comment]
Thank you for pointing that out. I guess my finger didn't let go of the shift when typing the d. I fixed it.

**Pull request merged**
